apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: domix/demo-flux-cnmx:1.0.0
